sudo: required

services: docker

install:
- bundle install

script:
- bundle exec kitchen test

notifications:
  slack:
    secure: JC37Ukl9mLudrColpukt/TaZnsJ93waLLHx2kfDQQ1haiJ8NFd2TV0OEU2fSLwrQBcMo9u8eU9g6Joa5HGoB9UpJT5leH3p4lc2kcEYQLDUVNYV+kCVPyjtz4JIt3ifkZShLSWx5+TpS8482N9NFUEUGNqnDCkwq7IYBNVn2gJkgLz8U0Jd7Cw3ZHOi9unGLZbzdDFhQcclSq5svWqGu3tiU8XRVU3Gw24MA5hCeej+fknabdmOzXQOg4jJmEklf/8STjL3h1ljcgQM8WU+uf1vYR/oNVBpjR8WdXAkeNDB8sNENTpH/drr5yLd8Y5L2DCmI+B/eYqGB58X6yAt0Vo3oJadNh2gRS8b8D0pf9FUn9t3SeyWtavNA7itS10S3FNzy4ESlhNH13hqQHQNnm7QarruwXNBOCWxtR5DjBNwrnvk35nBuffy+1BhsguvTjplND8lNoziGAVzlHr6Pq265stPxCR41xd56PPwF+ny+Wd0PMoenl36D5XHCLQvLIJ4eSbbnJQGJLWPCi7DG06SgyzDN6Rrw1bKb3M7NmTIDeyKGMDEgJnDgchTx3wAKwzagtsOMvPBcM8imAzwqiJUboiHDY+W7O8nhDZtUS0jlsF/89L4O9ZSYXo6+Py2Uhuk+7PWaNQL1SyTE6ZYFbIi/2CuKgR4kjE5e9i0SPyI=
